apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - crossplane-kustomization.yaml
  - managed-resource-kustomization.yaml
  - mr-helm-kustomization.yaml
  - helmrepository-grafana.yaml
  - helmrepository-prometheus-community.yaml
  # - monitoring-kustomization.yaml
